FROM vigilart-base:latest AS builder

WORKDIR /app/frontend
RUN pnpm run build

FROM node:20-alpine AS runtime

WORKDIR /app/frontend

RUN corepack enable pnpm

COPY --from=builder /app/frontend/.next ./.next
COPY --from=builder /app/frontend/public ./public
COPY frontend/package.json ./

RUN pnpm install --prod --frozen-lockfile --ignore-scripts

ENV PORT=3000

CMD ["pnpm", "start"]
