services:

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile.prod
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DATABASE_URL: ${DATABASE_URL}
      SERVER_PORT: ${SERVER_PORT}
      NODE_ENV: ${NODE_ENV}
      API_BASE_URL: ${API_BASE_URL}
      API_PREFIX: ${API_PREFIX}
      CORS_ORIGINS: ${CORS_ORIGINS}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES: ${JWT_EXPIRES}
      SALT_ROUNDS: ${SALT_ROUNDS}
      REDIS_URL: ${REDIS_URL}
    restart: always

  frontend:
    build:
      context: .
      dockerfile: web-app/Dockerfile.prod
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
        NEXT_PUBLIC_APP_ENV: ${NEXT_PUBLIC_APP_ENV}
        NEXT_PUBLIC_APP_URL: ${NEXT_PUBLIC_APP_URL}
        API_URL: ${API_URL}
    ports:
      - "${APP_PORT}:${APP_PORT}"
    networks:
      - app-network
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
      NEXT_PUBLIC_APP_ENV: ${NEXT_PUBLIC_APP_ENV}
      NEXT_PUBLIC_APP_URL: ${NEXT_PUBLIC_APP_URL}
      API_URL: ${API_URL}
    restart: always

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_prod_data:

networks:
  app-network:
    name: app-network