services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile.dev
    env_file:
      - .env
    volumes:
      - ./backend:/app/backend
      - ./shared:/app/shared
      - backend_node_modules:/app/backend/node_modules
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - prisma-network

  frontend:
    build:
      context: .
      dockerfile: web-app/Dockerfile.dev
    env_file:
      - .env
    volumes:
      - ./web-app:/app/web-app
      - ./shared:/app/shared
      - web_app_node_modules:/app/web-app/node_modules
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"

  db:
    image: postgres:16
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PORT: ${DB_PORT}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - postgres_local_data:/var/lib/postgresql/data
    networks:
      - prisma-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 10
    command: postgres -c listen_addresses='*'
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  prisma-studio:
    image: node:lts-alpine3.17
    working_dir: /app/backend
    volumes:
      - .:/app
    command: sh -c "corepack enable && corepack prepare pnpm@10.20.0 --activate && pnpm dlx prisma@6.19.0 studio --port 5555 --browser none"
    ports:
      - "5555:5555"
    env_file:
      - .env
    networks:
      - prisma-network
    depends_on:
      db:
        condition: service_healthy
      backend:
        condition: service_started

volumes:
  postgres_local_data:
  backend_node_modules:
  web_app_node_modules:

networks:
  prisma-network:
    name: prisma-network
