FROM node:22-alpine

WORKDIR /app

RUN corepack enable && corepack prepare pnpm@10.20.0 --activate

COPY pnpm-workspace.yaml pnpm-lock.yaml package.json tsconfig.base.json ./

COPY backend/package.json backend/
COPY shared/package.json shared/

RUN pnpm install

CMD ["sh", "-c", "pnpm --filter backend db:deploy && pnpm dev:backend"]
