name: "User Story"
description: "Template for writing user stories"
title: "Story: "
labels: ["type:story"]
body:
  - type: textarea
    id: user-story
    attributes:
      label: "🎯 User Story"
      value: "As a [role], I want [goal] so that [value]."
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: "✅ Acceptance Criteria"
      description: "List testable outcomes that QA can check."
      value: "- [ ] ..."
    validations:
      required: true

  - type: textarea
    id: definition-of-done
    attributes:
      label: "📌 Definition of Done"
      description: "Checklist of what must be true for this story to be complete (e.g., code merged, QA tested, docs updated)."
      value: "- [ ] Code pushed, reviewed and merged\n- [ ] QA tested on dev branch\n- [ ] At least 1 happy-path test (the feature works in the normal case).\n- [ ] At least 1 error-handling test passes.\n- [ ] Documentation updated\n- [ ] Story reviewed and accepted by the team/PM\n- [ ] Must meets AC and NFR\n- [ ] Must comply with the accessibility and security requirements\n"

  - type: textarea
    id: non-functional
    attributes:
      label: "⚙️ Non-Functional Requirements"
      description: "Includes performance, security, etc."
      placeholder: "E.g. performance, security, reliability, scalability, privacy, compliance..."

  - type: textarea
    id: dependencies
    attributes:
      label: "🔗 Dependencies"
      description: "List blocking features or other user stories this depends on."
      placeholder: "e.g. Needs user authentication"

  - type: textarea
    id: mockups
    attributes:
      label: "🎨 Mockups / UX Reference"
      description: "Link to Figma, screenshots, or other UX references."
