FROM node:22-alpine

WORKDIR /app

RUN corepack enable && corepack prepare pnpm@10.20.0 --activate

COPY pnpm-workspace.yaml pnpm-lock.yaml package.json tsconfig.base.json ./

COPY web-app/package.json web-app/
COPY shared/package.json shared/

RUN pnpm install

CMD ["pnpm", "dev:frontend"]
