FROM local/vigilart-base:latest AS builder

WORKDIR /app/web-app

COPY web-app/ .

RUN pnpm build

FROM node:22-alpine AS web-app-prod

WORKDIR /app

COPY --from=builder /app/web-app/.next ./.next
COPY --from=builder /app/web-app/public ./public
COPY web-app/package.json ./

RUN corepack enable && corepack prepare pnpm@10.20.0 --activate

EXPOSE 3000

CMD ["pnpm", "start:frontend"]
