FROM local/vigilart-base:latest AS builder

WORKDIR /app/web-app

COPY web-app/ .

RUN pnpm build

FROM node:22-alpine AS web-app-prod

WORKDIR /app

COPY --from=builder /app/web-app/.next ./.next
COPY --from=builder /app/web-app/public ./public
COPY --from=builder /app/web-app/package.json ./package.json

EXPOSE 3000

CMD ["node", "node_modules/.bin/next", "start", "--turbo"]
