name: Deploy to Prod

on:
  push:
    branches:
      - main

jobs:
  deploy-prod:
    name: Deploy to Prod Server
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH to Prod
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PROD_SSH_HOST }}
          username: ${{ secrets.PROD_SSH_USER }}
          key: ${{ secrets.PROD_SSH_KEY }}
          port: ${{ secrets.PROD_SSH_PORT || 22 }}
          script: |
            cd /srv/VigilArt
            sudo ./deploy.sh
