name: Repo mirroring to Epitech

on:
  push:
    branches:
      - main

jobs:
  mirror:
    if: github.repository != 'EpitechPGE45-2025/G-EIP-700-PAR-7-1-eip-39'
    name: 🔄 Mirror Repository
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: ${{ vars.EPITECH_REPO_URL }}
          ssh_private_key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}